import { Head, Html, Main, NextScript } from "next/document";
import { setColorsByTheme } from "../theme";

export function MagicScriptTag() {
  const boundFn = String(setColorsByTheme);
  const calledFunction = `(${boundFn})()`;

  // calledFunction = Terser.minify(calledFunction).code;

  // eslint-disable-next-line react/no-danger
  return <script dangerouslySetInnerHTML={{ __html: calledFunction }} />;
}

const Styles = () => {
  const s = `
    html {
      background-color: var(--color-bg);
      color: var(--color-fg);
    }`;

  return <style>{s}</style>;
};

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
          rel="stylesheet"
        />
        <Styles />
      </Head>
      <body>
        <MagicScriptTag />
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
