export const compsRaw = [
  "src/base/Animation/Animation",
  "src/base/BaseModal/BaseModal",
  "src/base/Image/Image",
  "src/base/Input/Input",
  "src/base/Lottie/Lottie",
  "src/base/Spacer/Spacer",
  "src/base/Sticker/Sticker",
  "src/base/VirtualizedList/VirtualizedList",
  "src/atoms/Badge/Badge",
  "src/atoms/Checkbox/Args",
  "src/atoms/Checkbox/Checkbox",
  "src/atoms/DividerLine/DividerLine",
  "src/atoms/Loader/Loader",
  "src/atoms/LogoText/LogoText",
  "src/atoms/Overlay/Overlay",
  "src/atoms/Paper/Paper",
  "src/atoms/RadioButton/RadioButton",
  "src/atoms/Skeleton/Skeleton",
  "src/atoms/ToggleButton/ToggleButton",
  "src/atoms/Typography/Typography",
  "src/molecules/AccordionItem/AccordionItem",
  "src/molecules/AccountAvatar/AccountAvatar",
  "src/molecules/AccountListItem/AccountListItem",
  "src/molecules/Alert/Alert",
  "src/molecules/AudioVisualizer/AudioVisualizer",
  "src/molecules/AuthenticatorBlock/AuthenticatorBlock",
  "src/molecules/Avatar/Avatar",
  "src/molecules/Breadcrumb/Breadcrumb",
  "src/molecules/Bullet/Bullet",
  "src/molecules/Button/Button",
  "src/molecules/Calendar/Calendar",
  "src/molecules/CarouselNavigationDots/CarouselNavigationDots",
  "src/molecules/CategoryListItem/CategoryListItem",
  "src/molecules/ChatBalloon/ChatBalloon",
  "src/molecules/ChatInput/ChatInput",
  "src/molecules/Chip/Chip",
  "src/molecules/ChipAvatar/ChipAvatar",
  "src/molecules/ChipsDropdown/ChipsDropdown",
  "src/molecules/CircularProgressBar/CircularProgressBar",
  "src/molecules/CompactExpandableAccount/CompactExpandableAccount",
  "src/molecules/ComposableTypography/ComposableTypography",
  "src/molecules/ComposedElement/ComposedElement",
  "src/molecules/Disclaimer/Disclaimer",
  "src/molecules/DraggableList/DraggableList",
  "src/molecules/ExpandableListElement/ExpandableListElement",
  "src/molecules/FileControl/FileControl",
  "src/molecules/HeaderTitle/HeaderTitle",
  "src/molecules/IconButton/IconButton",
  "src/molecules/InputAttach/InputAttach",
  "src/molecules/InputField/InputField",
  "src/molecules/InputSelect/InputSelect",
  "src/molecules/InputTextBlock/InputTextBlock",
  "src/molecules/LineAreaChart/LineAreaChart",
  "src/molecules/LineAreaHistoryChart/LineAreaHistoryChart",
  "src/molecules/Link/Link",
  "src/molecules/List/List",
  "src/molecules/ListTextBlockElement/ListTextBlockElement",
  "src/molecules/MultiAvatar/MultiAvatar",
  "src/molecules/NavigationListItem/NavigationListItem",
  "src/molecules/NavigationSwitch/NavigationSwitch",
  "src/molecules/PDFViewer/PDFViewer",
  "src/molecules/Pagination/Pagination",
  "src/molecules/PeriodCycleMenu/PeriodCycleMenu",
  "src/molecules/Popper/Popper",
  "src/molecules/PopupMenu/PopupMenu",
  "src/molecules/ProgressBar/ProgressBar",
  "src/molecules/RoundButton/RoundButton",
  "src/molecules/RoundButtonExpanded/RoundButtonExpanded",
  "src/molecules/RoundIcon/RoundIcon",
  "src/molecules/RoundIcon/RoundIcon",
  "src/molecules/Search/Search",
  "src/molecules/SearchInput/SearchInput",
  "src/molecules/SegmentedContentArea/SegmentedContentArea",
  "src/molecules/SegmentedProgressBar/SegmentedProgressBar",
  "src/molecules/SideButton/SideButton",
  "src/molecules/Slider/Slider",
  "src/molecules/SliderButton/SliderButton",
  "src/molecules/SquareFilter/SquareFilter",
  "src/molecules/Tab/Tab",
  "src/molecules/TabNavigationSwitch/TabNavigationSwitch",
  "src/molecules/TabProgressBar/TabProgressBar",
  "src/molecules/Tag/Tag",
  "src/molecules/TextBlock/TextBlock",
  "src/molecules/TextBlockBullet/TextBlockBullet",
  "src/molecules/TextBlockPrivacy/TextBlockPrivacy",
  "src/molecules/TextCheckbox/TextCheckbox",
  "src/molecules/TextRadioButton/TextRadioButton",
  "src/molecules/Title/Title",
  "src/molecules/Toast/Toast",
  "src/molecules/Tooltip/Tooltip",
  "src/molecules/TransactionListElement/TransactionListElement",
  "src/molecules/VerticalChartBars/VerticalChartBars",
  "src/molecules/VoiceVisualizer/VoiceVisualizer",
  "src/organisms/Accordion/Accordion",
  "src/organisms/AccountList/AccountList",
  "src/organisms/AccountsCarousel/AccountsCarousel",
  "src/organisms/BankCardCarousel/BankCardCarousel",
  "src/organisms/Banner/BannerBackgroundImage",
  "src/organisms/Banner/BannerComposableTypography",
  "src/organisms/Banner/BannerMainImage",
  "src/organisms/Banner/BannerText",
  "src/organisms/Banner/Banner",
  "src/organisms/Callout/Callout",

  "src/organisms/Card.BankCard",
  "src/organisms/Card.BaseCard",
  "src/organisms/Card.GalleryCard",
  "src/organisms/Card.WidgetCard",
  "src/organisms/Card.AccountCard",
  "src/organisms/Card.AccountRowCard",
  "src/organisms/Card.ClientCard",
  "src/organisms/Card.DocumentCard",
  "src/organisms/Card.GenericCard",
  "src/organisms/Card.NavigationCard",
  "src/organisms/Card.SignDocCard",

  "src/organisms/Carousel/Carousel",
  "src/organisms/CategoryCarousel/CategoryCarousel",
  "src/organisms/ChipsCarousel/ChipsCarousel",
  "src/organisms/CoachMark/CoachMark",
  "src/organisms/CustomTable/CustomTable",
  "src/organisms/DatePicker/DatePicker",
  "src/organisms/DescriptionTextList/DescriptionTextList",
  "src/organisms/DraggableGrid/DraggableGrid",
  "src/organisms/Drawer/Drawer",
  "src/organisms/ExpandableList/ExpandableList",
  "src/organisms/FeedbackModal/FeedbackModal",
  "src/organisms/FilterBlock/FilterBlock",
  "src/organisms/FooterContainer/FooterContainer",
  "src/organisms/FooterNavBar/FooterNavBar",
  "src/organisms/GalleryCardCarousel/GalleryCardCarousel",
  "src/organisms/HeaderNavBar/HeaderNavBar",
  "src/organisms/InputNote/InputNote",
  "src/organisms/InputPhone/InputPhone",
  "src/organisms/InputSlider/InputSlider",
  "src/organisms/LateralMenu/LateralMenu",
  "src/organisms/LineChart/LineChart",
  "src/organisms/Modal/Modal",
  "src/organisms/MultilayerModal/MultilayerModal",
  "src/organisms/NavBarMenu/NavBarMenu",
  "src/organisms/NavigationList/NavigationList",
  "src/organisms/ProfileMenu/ProfileMenu",
  "src/organisms/ReanimatedCarousel/ReanimatedCarousel",
  "src/organisms/SideBarMenu/SideBarMenu",
  "src/organisms/SideBarWidget/SideBarWidget",
  "src/organisms/SideButtonMenu/SideButtonMenu",
  "src/organisms/SlideShow/SlideShow",
  "src/organisms/Stepper/Stepper",
  "src/organisms/Table/Table",
  "src/organisms/Tabs/Tabs",
  "src/organisms/TagFilterCarousel/TagFilterCarousel",
  "src/organisms/Timeline/Timeline",
  "src/organisms/TransactionDetail/TransactionDetail",
  "src/organisms/TransactionList/TransactionList",
  "src/organisms/TransactionManagerDetail/TransactionManagerDetail",
  "src/organisms/Walkthrough/Walkthrough",
];

// const wait = () =>
//   new Promise((res) => {
//     setTimeout(() => {
//       res(null);
//     }, 500);
//   });

// const compsMap = () => {
//   const mapped = compsRaw.map((path) => {
//     const [src, category, component] = path.split("/");

//     return {
//       src,
//       category,
//       component,
//     };
//   });

//   return uniqBy(mapped, "component");
//   // return mapped;
// };

// const batch = async () => {
//   const data = compsMap();

//   for (const { category, component } of data) {
//     await create({
//       componentData: {
//         name: component,
//         category: category.toUpperCase(),
//         description: null,
//       },
//     });
//     await wait();
//     console.log({
//       name: component,
//       category: category.toUpperCase(),
//       description: null,
//     });
//   }
// };
// const { mutateAsync: create } = trpc.components.create.useMutation();
