export const c18Quotes = [
  "Bring it on!",
  "Fine, I'll take care of this.",
  "Is this really the time to be fighting me?",
  "Is it time for a rematch?",
  "I hear you defeated Cell for us.",
  "So, you killed Krillin a long time ago?",
  "It's been a while, Trunks.",
  "What was I like in your world?",
  "I consider this to be a bit of revenge!",
  "What's your business with us now?",
  "Looks like we can finally finish our tournament fight.",
  "You two are in need of some harsh discipline!",
  "I guess I can give you some pointers.",
  "You haven't gotten rusty on me, have you?",
  "Don't you dare turn me into chocolate again, okay?",
  "What are you gonna turn me into this time?",
  "Long time, no see...16.",
  "You were…alive all this time?",
  "This guy isn't even a fighter anymore.",
  "How are my favorite scholar's studies coming along?",
  "I'd appreciate if you took it easy on me.",
  "Vegeta, you never grow up!",
  "Oh? That's a familiar face...",
  "21? Doesn't ring a bell.",
  "Another android? Give me a break.",
  "You're looking better than usual today.",
  "I don't see what all the fuss is about.",
  "Later.",
  "How about going home for once?",
  "Tch, another outfit ruined.",
  "That was a repeat in more ways than one!",
  "Did you really beat Cell like that?",
  "You have to pay with interest for what you did to Krillin!",
  "You won't get another chance to kill Krillin!",
  "Go away. You annoy me.",
  "I'm not impressed...with you or my future self.",
  "I'm not the same as the one you encountered!",
  "You don't need me if you have that form, right?",
  "You're not absorbing me again!",
  "Quit clowning around already!",
  "You kids... You're a real headache!",
  "I have higher expectations of you than that!",
  "What's with that look! I didn't fall in love with a sniveling coward!",
  "I don't want to play with you ever again.",
  "A diet like that would turn anyone into a massive blob.",
  "Hey...you held back, didn't you?",
  "Sorry, 16! Looks like I win this one!",
  "Have you been spending too much time reading books?",
  "Give me a break! This was too easy...",
  "You should've told me you weren't holding back!",
  "I'd be feeling blue too.",
  "I guess you aren't who I thought you were.",
  "Are you...a mother too?",
  "Dr. Gero was always a clever one...",
  "No Super Saiyan this time? You deserved that beating.",
  "If you drag me into a fight, you're gonna pay a hefty price.",
  "Is that really it? I was expecting a little more fun.",
  "So, you finally understand who's stronger? Moron.",
  "Wow, that was almost impressive. Can we take the kids gloves off next time, then?",
  "You knew you'd lose, but you challenged me anyway. That curiosity is gonna get you killed.",
  "You really do look like your having fun. Fighting with you almost makes me feel like a kid.",
  "So you wanna settle our old score? Nah... Heh heh, I'm just kidding.",
  "You have the power of Kami, even if you aren't at all like him.",
  "I'm not the same as my future self. I'll help you out a bit, if I can.",
  "You'll never absorb us with that kind of performance.",
  "Not bad, runts. Not bad.",
  "Krillin is the man I married. He won't leave me just because of a little scrap.",
  "I never thought we'd have to fight together. Thanks for the help, 16.",
  "Don't expect any gratitude out of me. You just want to eat, don't you?",
];

export const c18AngryQuotes = [
  "I don't want to play with you ever again.",
  "You kids... You're a real headache!",
  "I have higher expectations of you than that!",
  "You knew you'd lose, but you challenged me anyway. That curiosity is gonna get you killed.",
  "You'll never absorb us with that kind of performance.",
  "You don't need me if you have that form, right?",
  "You two are in need of some harsh discipline.",
  "I'm not the same as my future self. I'll help you out a bit, if I can.",
  "Is that really it? I was expecting a little more fun.",
  "Quit clowning around already!",
  "I'd appreciate if you took it easy on me.",
];
